[package]
name = "bizarre_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bizarre_memory = { version = "0.1.0", path = "../bizarre_memory" }
thiserror = { workspace = true }
