[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bizarre_engine = { version = "0.1.0", path = "../crates/bizarre_engine" }
nalgebra-glm = { workspace = true }
anyhow = { workspace = true }
