[workspace]
resolver = "2"
members = [
    "sandbox",
    "crates/bizarre_app",
    "crates/bizarre_window",
    "crates/bizarre_event",
    "crates/bizarre_engine",
]
default-members = ["sandbox", "crates/bizarre_engine"]

[workspace.dependencies]
nalgebra-glm = "0.18.0"
anyhow = "1.0.82"
