[package]
name = "bizarre_app"
version = "0.1.0"
edition = "2021"

[dependencies]
bizarre_core = { version = "0.1.0", path = "../bizarre_core" }
bizarre_event = { version = "0.1.0", path = "../bizarre_event" }

anyhow = { workspace = true }
